version: '3.9'
services:
  java_app:
    container_name: java_app
    image: ms-register-app:0.0.1
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASS=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=true
      - DEBUG_LEVEL=info
    depends_on:
      - java_db
      - redis
  java_db:
    container_name: java_db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379